//! # Rusty Link
//!
//! Rusty Link is a Rust wrapper of [abl_link](https://github.com/Ableton/link/tree/master/extensions/abl_link), which
//! is a C 11 wrapper made by Ableton for their C++ codebase.
//! This library attempts to be as unopinionated and plain as possible in
//! copying the functionality of abl_link, while hiding unsafe behaviour and
//! providing Rust's guarantees.
//!
//! See [README.md](https://github.com/anzbert/rusty_link) for more info.

// PRIVATE
#[allow(non_camel_case_types)]
pub(crate) mod rust_bindings {
    // Rust bindings of all functions and types starting with 'abl_link_' from
    // 'abl_link.h' (generated by bindgen)
    include!(concat!(env!("OUT_DIR"), "/link_bindings.rs"));
}

pub(crate) mod abl_link;
pub(crate) mod session_state;

// PUBLIC API
pub use abl_link::AblLink;
pub use session_state::SessionState;
