//! # Rusty Link
//!
//! Rusty Link provides bindings to [`abl_link`](https://github.com/Ableton/link/tree/master/extensions/abl_link),
//! which is a C 11 wrapper made by Ableton for their C++ codebase.
//! This library attempts to be fairly plain and unoppinionated in
//! copying the functionality of `abl_link`, while providing Rust's safety guarantees.
//!
//! See [README.md](https://github.com/anzbert/rusty_link) for more info.

// PRIVATE
#[allow(non_camel_case_types)]
mod rust_bindings {
    // Rust bindings of all functions and types starting with 'abl_link_' from
    // 'abl_link.h' (generated by bindgen)
    include!(concat!(env!("OUT_DIR"), "/link_bindings.rs"));
}

mod abl_link;
mod host_time_filter;
mod session_state;
mod split;

// PUBLIC API
pub use abl_link::AblLink;
pub use host_time_filter::HostTimeFilter;
pub use session_state::SessionState;
